### ISSUE TITLE
Default value of negative infinity for args breaks schema definitions

### ISSUE THREAD

**Issue by TSiege** [facebook/graphql#310]
When I was writing a custom connection, I added a field to `args` with a `defaultValue` of `-Infinity`, which ended up breaking the schema generation. I was still able to query the Graph API via graphiql, but I received this error message and had no access to documentation.

```
GraphQLError
    at r (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:549156)
    at d (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:290786)
    at p (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:290452)
    at u (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:289639)
    at Object.i [as advance] (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:287893)
    at ee (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:251214)
    at i (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:243452)
    at S (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:560024)
    at https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:286709
    at Array.reduce (native)
```

my code looked like this
```js
...
args: Object.assign({
  min: {
    type: GraphQLFloat, defaultValue: -Infinity
  },
}, connectionArgs),
...
```

**Comment by TOTBWF** [comment]
This repo is for discussing the Graphql specification, and this seems more like an implementation issue. I would suggest reporting this to the maintainers of whatever libraries/APIs you are using

**Comment by TSiege** [comment]
sorry was in the wrong one! I'll close

**Comment by TOTBWF** [comment]
No worries :smile:
